repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--show-error-codes, --ignore-missing-imports]
        files: common/.*
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8 common
        files: common/.*
      - id: flake8
        name: flake8 test
        files: common/.*
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
