repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--show-error-codes, --ignore-missing-imports,
               --strict, --disallow-any-generics,
               --warn-unused-ignores,
               --disallow-subclassing-any,
               --disallow-untyped-calls,
               --warn-redundant-casts,
               --warn-return-any,
               --warn-unreachable,
               --disallow-untyped-decorators,
               --disallow-incomplete-defs, --disallow-untyped-defs,
               --follow-imports, skip]
        files: common/.*
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-tidy-imports
          - flake8-import-order
        name: flake8 common
        files: common/.*
      - id: flake8
        name: flake8 test
        files: common/.*
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
