[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  | README.md
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pydocstyle]
ignore = ["D100", "D101", "D104", "D105","D400", "D415", "D210", "D213", "D413", "D203", "D212", "D205", "D401"]

[tool.mypy]
python_version = 3.7

[[tool.mypy.overrides]]
module = "pandas"
ignore_missing_imports = true
