name: Tests

on:
  # Manually triggerable in github
  workflow_dispatch:

  # When a push occurs on either of these branches
  push:
    branches:
      - master
      - development

  # When a push occurs on a PR that targets these branches
  pull_request:
    branches:
      - master
      - development

  schedule:
    # Every day at 7AM UTC
    - cron: '0 07 * * *'

env:

  # Arguments used for pytest
  pytest-args: >-
    --forked
    --durations=20
    --timeout=300
    --timeout-method=thread
    -s

  # Arguments used for code-cov which is later used to annotate PR's on github
  code-cov-args: >-
    --cov=automl_common
    --cov-branch
    --cov-report=xml

jobs:

  ubuntu:

    name: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.kind }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        kind: ['source']

        exclude:
          # Exclude windows as bash commands wont work in windows runner
          - os: windows-latest

          # Exclude macos as there are permission errors using conda as we do
          - os: macos-latest

        include:
          # Add the tag code-cov to ubuntu-3.7-source
          - os: ubuntu-latest
            python-version: 3.7
            kind: 'source'
            code-cov: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Tests
      timeout-minutes: 20
      run: |
        if [ ${{ matrix.code-cov }} ]; then
          $PYTHON -m pytest ${{ env.pytest-args }} ${{ env.code-cov-args }} test
        else
          $PYTHON -m pytest ${{ env.pytest-args }} test
        fi

    - name: Check for files left behind by test
      if: ${{ always() }}
      run: |
        before="${{ steps.status-before.outputs.BEFORE }}"
        after="$(git status --porcelain -b)"
        if [[ "$before" != "$after" ]]; then
            echo "git status from before: $before"
            echo "git status from after: $after"
            echo "Not all generated files have been deleted!"
            exit 1
        fi

    - name: Upload coverage
      if: matrix.code-cov && always()
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
